### ISSUE TITLE
Pasting fails if text to be pasted contains only one line

### ISSUE THREAD

**Issue by dp-alvarez** [sunhs/py-paste-indent#4]
First of all, thanks for the great extension! It is baffling that such an essential feature is missing from the official vscode python extension.

I was trying to override the default paste action with your extension (I see no case in which I would want my code to be pasted with the wrong indentation) when I stumbled across this issue.
It seems your extension is only able to paste is the text to be pasted contains at least one newline. If it doesn't no text is pasted.
Simply trying to copy and paste a single line in a python file should be enough to replicate the issue.

Fixing this would allow to replace the default paste action with the one in your extension, which I'd very much like to do!

**Comment by sunhs** [comment]
Sorry for the late reply.
Version 0.1.4 may have resolved your problem.
Let me know if it fits your need.

**Comment by dp-alvarez** [comment]
I tested it and apparently works great!
Will continue using it and report any issues.

Thank you very much, seems like an simple feature but it was driving me crazy that VSCode didn't have it!
